# Generated by Django 4.1.2 on 2022-10-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('MATH', 'Math Game'), {'Anagram Game', 'ANAGRAM'}], default='MATH'),
        ),
    ]
