# Generated by Django 4.1.2 on 2022-10-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_delete_game_delete_gamescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.TextField(max_length=200)),
                ('high_score', models.IntegerField(null=True)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('game', models.TextField(choices=[('MATH', 'Math Game'), {'Anagram Game', 'ANAGRAM'}], default='MATH')),
                ('score', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
