# Generated by Django 4.1.2 on 2022-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamescore_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='user_name',
            field=models.TextField(),
        ),
    ]
