# Generated by Django 4.1.2 on 2022-10-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_gamescore_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='max_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='operation',
            field=models.TextField(null=True),
        ),
    ]
