# Generated by Django 4.1.2 on 2022-10-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamescore_max_number_gamescore_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='word_length',
            field=models.IntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
