# Generated by Django 4.1.2 on 2022-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamescore_word_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='word_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
